const MAINDOMAIN = `http://crong.codesquad.kr:8080`
const WOOWADOMAIN = `${MAINDOMAIN}/woowa`
const TABURL = `${WOOWADOMAIN}/best`;
const MAIN_SLIDELISTURL = `${WOOWADOMAIN}/main`;
const COURSE_SLIDELISTURL = `${WOOWADOMAIN}/course`;
const SOUP_SLIDELISTURL = `${WOOWADOMAIN}/soup`;
const SIDE_SLIDELISTURL = `${WOOWADOMAIN}/side`;
const SEARCHURL = `${MAINDOMAIN}/ac`


export default {
  MAINDOMAIN,
  WOOWADOMAIN,
  TABURL,
  SEARCHURL,
  MAIN_SLIDELISTURL,
  COURSE_SLIDELISTURL,
  SOUP_SLIDELISTURL,
  SIDE_SLIDELISTURL
}